server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_db?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: khweb
    password: khweb@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL8Dialect
#    initialization-mode: always

  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generate-ddl: true
#    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create
        show_sql: true
        use_sql_comments: true
#      properties:
#        hibernate:
#          ddl-auto: create-drop
#          show_sql: true
#          format_sql: true
#          use_sql_comments: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org:
      hibernate:
        format_sql: DEBUG