spring:
#  security:
#    user:
#      name: user
#      password: 1111
#      ??? ?????? ???
  profiles:
  datasource:
    url: jdbc:h2:tcp://localhost/~/basicsecurity
    username: sa
    password:
    driver-class-name: org.h2.Driver