spring:
  profiles:
    default: mysql

---

spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;
      username: sa
      password:
      driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: embedded
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    url: jdbc:mysql://localhost:3306/springbatch?useSSL=false&allowPublicKeyRetrieval=true
    username: khweb
    password: khWeb@123
#    driver-class-name: com.mysql.jdbc.Driver
  batch:
#    스프링자동 막기 (수동실행시)
    job:
      enabled: false
    jdbc:
      initialize-schema: always

