server:
  port: 7777
spring:
#  Spring Boot??? ??? ?? ??? ??? ????.
#  ?? ??? /src/main/resources/application.yml ??? ???? FreeMarker ????? ??? ?? ??
  freemarker:
    cache: false
    template_update_delay: 0
    template-loader-path: classpath:/templates
    suffix: .ftl
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
